In [1]:
import os
print(os.getcwd())

C:\Abhishek college stuff\SEM2\ASEP-2\fraud-detection-ecommerce-main\fraud-detection-ecommerce-main\notebooks

In [2]:
import pandas as pd

df = pd.read_csv("../data/train_transaction.csv")
print(df.shape)

FileNotFoundError: [Errno 2] No such file or directory: '../data/train_transaction.csv'

In [2]:
import pandas as pd

df = pd.read_csv("../data/train_transaction.csv")
print(df.shape)

FileNotFoundError: [Errno 2] No such file or directory: '../data/train_transaction.csv'

In [3]:
import pandas as pd

df = pd.read_csv("../data/train_transaction.csv")
print(df.shape)

FileNotFoundError: [Errno 2] No such file or directory: '../data/train_transaction.csv'

In [4]:
df = pd.read_csv("../data/train_transaction.csv")
print(df.shape)

FileNotFoundError: [Errno 2] No such file or directory: '../data/train_transaction.csv'

In [5]:
import os
print(os.getcwd())

C:\Abhishek college stuff\SEM2\ASEP-2\fraud-detection-ecommerce-main\fraud-detection-ecommerce-main\notebooks

In [6]:
import os
print(os.listdir())

['.gitkeep', '.ipynb_checkpoints', '01_ieee_data_loading_and_eda.ipynb', 'Untitled.ipynb']

In [7]:
import pandas as pd

df = pd.read_csv("../data/train_transaction.csv")
print(df.shape)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/train_transaction.csv'

In [8]:
import pandas as pd

df = pd.read_csv("../data/train_transaction.csv")
print(df.shape)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/train_transaction.csv'

In [9]:
import pandas as pd

df = pd.read_csv("../data/train_transaction.csv")
print(df.shape)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/train_transaction.csv'

In [10]:
import os
print(os.getcwd())

C:\Abhishek college stuff\SEM2\ASEP-2\fraud-detection-ecommerce-main\fraud-detection-ecommerce-main\notebooks

In [11]:
import pandas as pd

df = pd.read_csv("C:/Abhishek college stuff/SEM2/ASEP-2/fraud-detection-ecommerce-main/fraud-detection-ecommerce-main/data/train_transaction.csv")

print(df.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Abhishek college stuff/SEM2/ASEP-2/fraud-detection-ecommerce-main/fraud-detection-ecommerce-main/data/train_transaction.csv'

In [12]:
import os

base_path = r"C:\Abhishek college stuff\SEM2\ASEP-2\fraud-detection-ecommerce-main\fraud-detection-ecommerce-main\data"
file_path = os.path.join(base_path, "train_transaction.csv")

print(file_path)
print(os.path.exists(file_path))

C:\Abhishek college stuff\SEM2\ASEP-2\fraud-detection-ecommerce-main\fraud-detection-ecommerce-main\data\train_transaction.csv
False

In [13]:
import pandas as pd

df = pd.read_csv(file_path)
print(df.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Abhishek college stuff\\SEM2\\ASEP-2\\fraud-detection-ecommerce-main\\fraud-detection-ecommerce-main\\data\\train_transaction.csv'

In [14]:
import os

base = r"C:\Abhishek college stuff\SEM2\ASEP-2"

for root, dirs, files in os.walk(base):
    if "train_transaction.csv" in files:
        print("FOUND:", os.path.join(root, "train_transaction.csv"))

In [15]:
import os

print(os.listdir(r"C:\Abhishek college stuff\SEM2\ASEP-2\fraud-detection-ecommerce-main\fraud-detection-ecommerce-main\data"))

['.gitkeep', '.ipynb_checkpoints', 'README.md', 'train_identity.csv', 'train_transaction.csv', 'Untitled.ipynb']

In [16]:
import pandas as pd

df = pd.read_csv("../data/train_transaction.csv")
print(df.shape)

(506691, 393)

In [17]:
identity = pd.read_csv("../data/train_identity.csv")
print(identity.shape)

(141907, 41)

In [18]:
df = df.merge(identity, on="TransactionID", how="left")
print(df.shape)

(506691, 433)

In [19]:
print(df['isFraud'].value_counts())

KeyError: 'isFraud'

In [20]:
print(df.columns)

Index(['TransactionID', 'TransactionDT', 'TransactionAmt', 'ProductCD',
       'card1', 'card2', 'card3', 'card4', 'card5', 'card6',
       ...
       'id-31', 'id-32', 'id-33', 'id-34', 'id-35', 'id-36', 'id-37', 'id-38',
       'DeviceType', 'DeviceInfo'],
      dtype='str', length=433)

In [21]:
df = pd.read_csv("../data/train_transaction.csv")
identity = pd.read_csv("../data/train_identity.csv")

df = df.merge(identity, on="TransactionID", how="left")

In [22]:
print(df['isFraud'].value_counts())

KeyError: 'isFraud'

In [23]:
print(df.columns.tolist())

['TransactionID', 'TransactionDT', 'TransactionAmt', 'ProductCD', 'card1', 'card2', 'card3', 'card4', 'card5', 'card6', 'addr1', 'addr2', 'dist1', 'dist2', 'P_emaildomain', 'R_emaildomain', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13', 'C14', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51', 'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61', 'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71', 'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81', 'V82', 'V83', 'V84', 'V85', 'V86', 'V87', 'V88', 'V89', 'V90', 'V91', 'V92', 'V93', 'V94', 'V95', 'V96', 'V97', 'V98', 'V99', 'V100', 'V101', 'V102', 'V103', 'V104', 'V105', 'V106', 'V107', 'V108', 'V109', 'V110', 'V111', 'V112', 'V113', 'V114', 'V115', 'V116', 'V117', 'V118', 'V119', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V126', 'V127', 'V128', 'V129', 'V130', 'V131', 'V132', 'V133', 'V134', 'V135', 'V136', 'V137', 'V138', 'V139', 'V140', 'V141', 'V142', 'V143', 'V144', 'V145', 'V146', 'V147', 'V148', 'V149', 'V150', 'V151', 'V152', 'V153', 'V154', 'V155', 'V156', 'V157', 'V158', 'V159', 'V160', 'V161', 'V162', 'V163', 'V164', 'V165', 'V166', 'V167', 'V168', 'V169', 'V170', 'V171', 'V172', 'V173', 'V174', 'V175', 'V176', 'V177', 'V178', 'V179', 'V180', 'V181', 'V182', 'V183', 'V184', 'V185', 'V186', 'V187', 'V188', 'V189', 'V190', 'V191', 'V192', 'V193', 'V194', 'V195', 'V196', 'V197', 'V198', 'V199', 'V200', 'V201', 'V202', 'V203', 'V204', 'V205', 'V206', 'V207', 'V208', 'V209', 'V210', 'V211', 'V212', 'V213', 'V214', 'V215', 'V216', 'V217', 'V218', 'V219', 'V220', 'V221', 'V222', 'V223', 'V224', 'V225', 'V226', 'V227', 'V228', 'V229', 'V230', 'V231', 'V232', 'V233', 'V234', 'V235', 'V236', 'V237', 'V238', 'V239', 'V240', 'V241', 'V242', 'V243', 'V244', 'V245', 'V246', 'V247', 'V248', 'V249', 'V250', 'V251', 'V252', 'V253', 'V254', 'V255', 'V256', 'V257', 'V258', 'V259', 'V260', 'V261', 'V262', 'V263', 'V264', 'V265', 'V266', 'V267', 'V268', 'V269', 'V270', 'V271', 'V272', 'V273', 'V274', 'V275', 'V276', 'V277', 'V278', 'V279', 'V280', 'V281', 'V282', 'V283', 'V284', 'V285', 'V286', 'V287', 'V288', 'V289', 'V290', 'V291', 'V292', 'V293', 'V294', 'V295', 'V296', 'V297', 'V298', 'V299', 'V300', 'V301', 'V302', 'V303', 'V304', 'V305', 'V306', 'V307', 'V308', 'V309', 'V310', 'V311', 'V312', 'V313', 'V314', 'V315', 'V316', 'V317', 'V318', 'V319', 'V320', 'V321', 'V322', 'V323', 'V324', 'V325', 'V326', 'V327', 'V328', 'V329', 'V330', 'V331', 'V332', 'V333', 'V334', 'V335', 'V336', 'V337', 'V338', 'V339', 'id-01', 'id-02', 'id-03', 'id-04', 'id-05', 'id-06', 'id-07', 'id-08', 'id-09', 'id-10', 'id-11', 'id-12', 'id-13', 'id-14', 'id-15', 'id-16', 'id-17', 'id-18', 'id-19', 'id-20', 'id-21', 'id-22', 'id-23', 'id-24', 'id-25', 'id-26', 'id-27', 'id-28', 'id-29', 'id-30', 'id-31', 'id-32', 'id-33', 'id-34', 'id-35', 'id-36', 'id-37', 'id-38', 'DeviceType', 'DeviceInfo']

In [24]:
df.head()

,TransactionID,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,id-31,id-32,id-33,id-34,id-35,id-36,id-37,id-38,DeviceType,DeviceInfo
0,3663549,18403224,31.95,W,10409,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3663550,18403263,49.00,W,4272,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3663551,18403310,171.00,W,4476,574.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3663552,18403310,284.95,W,10989,360.0,150.0,visa,166.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3663553,18403317,67.95,W,18018,452.0,150.0,mastercard,117.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df.head()

,TransactionID,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,id-31,id-32,id-33,id-34,id-35,id-36,id-37,id-38,DeviceType,DeviceInfo
0,3663549,18403224,31.95,W,10409,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3663550,18403263,49.00,W,4272,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3663551,18403310,171.00,W,4476,574.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3663552,18403310,284.95,W,10989,360.0,150.0,visa,166.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3663553,18403317,67.95,W,18018,452.0,150.0,mastercard,117.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
print(df['isFraud'].value_counts())

KeyError: 'isFraud'